from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent

def write(path, text):
    file = ROOT / path
    file.parent.mkdir(parents=True, exist_ok=True)
    file.write_text(text.lstrip(), encoding="utf-8")

def sprint006():

    templates = {

"fastapi.py.j2":'''
from fastapi import FastAPI

app = FastAPI(title="{{ project_name }}")

@app.get("/")
def root():
    return {"status":"ok"}
''',

"nextjs.package.json.j2":'''
{
  "name":"oncehumantoolkit",
  "private":true
}
''',

"sqlite.py.j2":'''
import sqlite3

conn = sqlite3.connect("oncehuman.db")
''',

"readme.md.j2":'''
# {{ project_name }}

Generated by OnceHumanToolkit Generator
''',

"github.yml.j2":'''
name: CI

on:
  push:
    branches:
      - main
'''
    }

    for name,content in templates.items():
        write(f"generator/templates/{name}",content)

    write(
"generator/core/renderer.py",
'''
from pathlib import Path

class TemplateRenderer:

    def render(self,path,variables):

        text=Path(path).read_text(encoding="utf8")

        for k,v in variables.items():
            text=text.replace("{{ "+k+" }}",str(v))

        return text
'''
    )

    print("Sprint006 Complete")

if __name__=="__main__":

    if len(sys.argv)<2:
        raise SystemExit

    if sys.argv[1]=="sprint006":
        sprint006()
